import os
import glob
from PIL import Image

brain_dir = r"C:\Users\John Cornell\.gemini\antigravity\brain\36d67a62-dd9e-45a8-9e0a-e95d5c25dc22"
assets_dir = r"c:\Code\NPC\NPC.UI.Isometric\Assets"

if not os.path.exists(assets_dir):
    os.makedirs(assets_dir)

# Find all generated sprites
sprites = glob.glob(os.path.join(brain_dir, "iso_*.png"))

def is_background(pixel, filename):
    # Check if pixel is white or light gray (checkerboard)
    r, g, b = pixel[:3]
    # White
    if r > 240 and g > 240 and b > 240:
        if "sleeping" not in filename:
            return True
    # Grayscale checkerboard (r,g,b very close, and in range 140-200)
    if 140 < r < 200 and 140 < g < 200 and 140 < b < 200:
        if abs(r-g) < 10 and abs(r-b) < 10 and abs(g-b) < 10:
            return True
    return False

def remove_background_floodfill(img, filename):
    img = img.convert("RGBA")
    width, height = img.size
    pixels = img.load()
    
    # We will do a flood fill from all 4 corners
    corners = [(0,0), (width-1, 0), (0, height-1), (width-1, height-1)]
    queue = []
    visited = set()
    
    for c in corners:
        if is_background(pixels[c[0], c[1]], filename):
            queue.append(c)
            visited.add(c)
            
    # Flood fill
    directions = [(0,1), (0,-1), (1,0), (-1,0)]
    while queue:
        x, y = queue.pop(0)
        # Set to transparent
        pixels[x, y] = (0, 0, 0, 0)
        
        for dx, dy in directions:
            nx, ny = x + dx, y + dy
            if 0 <= nx < width and 0 <= ny < height:
                if (nx, ny) not in visited:
                    if is_background(pixels[nx, ny], filename):
                        visited.add((nx, ny))
                        queue.append((nx, ny))
                        
    return img

for sprite_path in sprites:
    filename = os.path.basename(sprite_path)
    clean_name = filename.split('_177')[0] + ".png" # Remove timestamp generated by generate_image
    
    img = Image.open(sprite_path)
    img = remove_background_floodfill(img, clean_name)
    
    # We will resize everything to 128x128 bounding box for easy drawing,
    # maintaining aspect ratio
    img.thumbnail((128, 128), Image.Resampling.LANCZOS)
    
    # Pad to exact 128x128
    padded = Image.new('RGBA', (128, 128), (0,0,0,0))
    offset = ((128 - img.width) // 2, (128 - img.height) // 2)
    padded.paste(img, offset)
    
    out_path = os.path.join(assets_dir, clean_name)
    padded.save(out_path, "PNG")
    print(f"Processed: {clean_name}")
